name: CI with Github Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome96-ff94
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "8"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run run:ci
          record: true
          continue-on-error: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
      - name: Generate Allure Report
        run: npm run generate-allurereports
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: Allure-report
          path: allure-report/

      - name: Copy allure report folder to public
        run: |
          mkdir public
          cp -R allure-report/* public
      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
