name: CI with Github Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome96-ff94
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run run:ci
          record: true
          continue-on-error: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
      - name: Generate Cucumber Report
        run: npm run report
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-cucumber-report
          path: reports/cucumber-report/

      - name: Copy cucumber report folder to public
        run: |
          mkdir public
          cp -R reports/cucumber-report/* public

      - name: Upload to S3 bucket
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: vwtestreports
          source_dir: public
      - name: Link To Report
        run: echo "https://vwtestreports.s3.eu-west-2.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html"
